### ISSUE TITLE
Github access token issue

### ISSUE THREAD

**Issue by Shelmith-Kariuki** [Displayr/flipData#1]
Hi, 

I am trying to install this package but I keep getting this error
![Githubissue](https://user-images.githubusercontent.com/37449624/69244251-af85f780-0bb5-11ea-9c2b-907caacca38d.PNG)

**Comment by Shelmith-Kariuki** [comment]
![Githubissues2](https://user-images.githubusercontent.com/37449624/69244338-d8a68800-0bb5-11ea-91ae-2e3862703301.PNG)

**Comment by Shelmith-Kariuki** [comment]
![Githubissues2](https://user-images.githubusercontent.com/37449624/69244480-12778e80-0bb6-11ea-8635-876c32b73abe.PNG)

**Comment by mwmclean** [comment]
Did you try following the instructions in the message?
```
usethis::browser_github_pat()
usethis::edit_r_environ()
```
If you don't want to use `usethis`, you need to go into your Settings on GitHub, create a new personal access token, then add it as an environment variable in R: `Sys.setenv(GITHUB_PAT = "[whatever_the_token_is]")`, and then try `install_github` again.
